services:
  drupal:
    image: drupal:10
    container_name: drupal
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      # Performance settings
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=300

      # Environment type
      - DRUPAL_ENV=development

    volumes:
      # Essential data only
      - ./database:/var/www/html/database # SQLite database (version controlled)
      - ./themes:/var/www/html/themes/custom # Your custom theme

    labels:
      - "app.name=portfolio-drupal"
      - "deployment.type=development"
