services:
  drupal:
    build: .
    container_name: drupal
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - DRUPAL_ENV=development
    volumes:
      - ./themes:/opt/drupal/web/themes/custom

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: for external DB access

volumes:
  postgres_data:
